version: "3"
services:
  gateway:
    image: swanpoi/gateway:5.0.0
    build:
      context: src/gateway
      dockerfile: Dockerfile

  cars:
    image: swanpoi/car-service:5.0.0
    build:
      context: src/car
      dockerfile: Dockerfile

  rental:
    image: swanpoi/rental-service:5.0.0
    build:
      context: src/rental
      dockerfile: Dockerfile

  payment:
    image: swanpoi/payment-service:5.0.0
    build:
      context: src/payment
      dockerfile: Dockerfile