zookeeper:
  image: confluentinc/cp-zookeeper:7.3.2
  ports:
    - name: client
      targetPort: 2181
    - name: jmx
      targetPort: 31000
  env:
    ZOOKEEPER_CLIENT_PORT: "2181"
    ZOOKEEPER_TICK_TIME: "2000"

kafka:
  name: kafka-svc # Имя будет использоваться в шаблоне Service
  replicas: 1
  image: confluentinc/cp-kafka:7.3.2
  ports:
    - name: internal
      targetPort: 29092
    - name: host
      targetPort: 9092
  env:
    KAFKA_BROKER_ID: "1"
    KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
    KAFKA_LISTENERS: "PLAINTEXT://0.0.0.0:29092,PLAINTEXT_HOST://0.0.0.0:9092"
    KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT"
    KAFKA_INTER_BROKER_LISTENER_NAME: "PLAINTEXT"
    KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://kafka-svc:29092,PLAINTEXT_HOST://localhost:9092"
    KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
    KAFKA_DEFAULT_REPLICATION_FACTOR: "1"
    KAFKA_MIN_INSYNC_REPLICAS: "1"
    KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: "1"
    KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: "1"
    KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: "1"
    
    KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: "100"