name: frontend
image:
  repository: swanpoi/rental-frontend
  tag: "1.0.0"
  pullPolicy: Always

replicaCount: 1
port: 80
serviceType: ClusterIP

resources:
  limits:
    cpu: 300m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi

healthCheck:
  enabled: false