apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}-svc
  labels:
    app: {{ .Values.name }}
spec:
  type: {{ .Values.serviceType }}
  selector:
    app: {{ .Values.name }}
  ports:
    - protocol: TCP
      port: {{ .Values.port }}
      targetPort: {{ .Values.port }}
      {{- if eq .Values.serviceType "NodePort" }}
      nodePort: {{ .Values.nodePort }}
      {{- end }}