commonLabels:
  project: car-rental-system

services:
  gateway:
    image: swanpoi/gateway:6.4.0
    pullPolicy: Always
    port: 8080
    nodePort: 30000
    serviceType: NodePort
    replicas: 1
    env:
      HOST: "0.0.0.0"
      PORT: "8080"
      REDIS_HOST: redis-svc
      REDIS_PORT: "6379"
      CAR_URL: http://cars-svc:8070/api/v1
      RENTAL_URL: http://rental-svc:8060/api/v1
      PAYMENT_URL: http://payment-svc:8050/api/v1
      OIDC_ISSUER_URL: "http://idp-svc:8090"
      OIDC_CLIENT_ID: "car-rental-client"
      OIDC_CLIENT_SECRET: "secret-gateway-bff-key"
      FRONTEND_URL: "http://localhost:3000" 
      IDP_PUBLIC_URL: "http://localhost:8090"
    healthCheck:
      enabled: true
      path: /manage/health
      readinessProbe:
        initialDelaySeconds: 10
        periodSeconds: 10
        timeoutSeconds: 5
        failureThreshold: 3
      livenessProbe:
        initialDelaySeconds: 30
        periodSeconds: 30
        timeoutSeconds: 5
        failureThreshold: 3

  cars:
    image: swanpoi/car-service:6.4.0
    pullPolicy: Always
    port: 8070
    serviceType: ClusterIP
    replicas: 1
    env:
      HOST: "0.0.0.0"
      PORT: "8070"
      DB_HOST: postgres-svc
      DB_PORT: "5432"
      DB_NAME: cars
      DB_USER: postgres
      DB_PASSWORD: "postgres"
      OIDC_ISSUER_URL: "http://idp-svc:8090" #"http://keycloak-svc:8080/realms/car-rental-system"
      OIDC_CLIENT_ID: "car-rental-client"
    healthCheck:
      enabled: true
      path: /manage/health
      readinessProbe:
        initialDelaySeconds: 10
        periodSeconds: 10
        timeoutSeconds: 5
        failureThreshold: 3
      livenessProbe:
        initialDelaySeconds: 30
        periodSeconds: 30
        timeoutSeconds: 5
        failureThreshold: 3

  rental:
    image: swanpoi/rental-service:6.4.0
    pullPolicy: Always
    port: 8060
    serviceType: ClusterIP
    replicas: 1
    env:
      HOST: "0.0.0.0"
      PORT: "8060"
      DB_HOST: postgres-svc
      DB_PORT: "5432"
      DB_NAME: rentals
      DB_USER: postgres
      DB_PASSWORD: "postgres"
      OIDC_ISSUER_URL: "http://idp-svc:8090" #"http://keycloak-svc:8080/realms/car-rental-system"
      OIDC_CLIENT_ID: "car-rental-client"
    healthCheck:
      enabled: true
      path: /manage/health
      readinessProbe:
        initialDelaySeconds: 10
        periodSeconds: 10
        timeoutSeconds: 5
        failureThreshold: 3
      livenessProbe:
        initialDelaySeconds: 30
        periodSeconds: 30
        timeoutSeconds: 5
        failureThreshold: 3

  payment:
    image: swanpoi/payment-service:6.0.0
    pullPolicy: Always
    port: 8050
    serviceType: ClusterIP
    replicas: 1
    env:
      HOST: "0.0.0.0"
      PORT: "8050"
      DB_HOST: postgres-svc
      DB_PORT: "5432"
      DB_NAME: payments
      DB_USER: postgres
      DB_PASSWORD: "postgres"
      OIDC_ISSUER_URL: "http://idp-svc:8090" #"http://keycloak-svc:8080/realms/car-rental-system"
      OIDC_CLIENT_ID: "car-rental-client"
    healthCheck:
      enabled: true
      path: /manage/health
      readinessProbe:
        initialDelaySeconds: 10
        periodSeconds: 10
        timeoutSeconds: 5
        failureThreshold: 3
      livenessProbe:
        initialDelaySeconds: 30
        periodSeconds: 30
        timeoutSeconds: 5
        failureThreshold: 3